config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    get 'maintenance/refresh_from_cheapthrills'
    resources :artists
    resources :venues
    resources :concerts
  end

  root 'static_page#homepage'

  get 'admin' => 'static_page#adminpage'

end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
	def homepage
		@concerts = Concert.all
	end
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/static_page/adminpage.html.erb
<%= render "shared/admin_nav" %>
<div class="jumbotron">
  <h1>Admin</h1>
</div>

app/views/static_page/homepage.html.erb
<div id="homepage" data-api="<%=url_for api_concerts_path(format: :json) %>">
  <table class="table">
      <thead>
      <tr>
        <th>&nbsp;</th>
        <th>Artist</th>
        <th>Date</th>
        <th>Time</th>
        <th>Venue</th>
        <th>Price</th>
      </tr>
    </thead>

    <tbody data-bind="foreach: concerts">
      <tr>
        <td>
          <!-- ko if: is_sold_out -->
          SOLD OUT
          <!-- /ko -->
        </td>
        <td>
          <a href="#" data-bind="text: artists_names, click: $parent.toggleArtists, clickBubble: false"></a>
          <div data-bind="foreach: artists, visible: artists_info_visible">
            <div class="media">
              <div class="media-left">
                <!-- ko if: artist_thumbnail_url -->
                  <img class="media-object" data-bind="attr: {src: artist_thumbnail_url, alt: name}">
                <!-- /ko -->
                <!-- ko ifnot: artist_thumbnail_url -->
                  <img class="media-object" src="http://placehold.it/640x640&text=vinyl+shop"  data-bind="attr: {alt: name}">
                <!-- /ko -->
              </div>
              <div class="media-body">
                <h4 class="media-heading" data-bind="text: name"></h4>
                <!-- ko if: embed_spotify -->
                <iframe data-bind="attr: {src: embed_spotify}" width="300" height="80" frameborder="0" allowtransparency="true"></iframe>
                <!-- /ko -->
              </div>
            </div>
          </div>
        </td>
        <td data-bind="text: formated_show_date"></td>
        <td data-bind="text: formated_show_time"></td>
        <td data-bind="text: venue.name"></td>
        <td data-bind="text: formated_price"></td>
      </tr>
    </tbody>
  </table>
</div>